"""BIST pazar sınıflandırması — YILDIZ PAZAR + ANA PAZAR.

Kaynak: KAP get_company_details (borsapy). Anlık görüntü: 2026-08-16.
Pazar atamaları zaman zaman değişir; yenilemek için scripts/build_markets.py yeniden çalıştırılır.
"""

YILDIZ_PAZAR = {
    "ADGYO.IS": "ADRA GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "AGESA.IS": "AGESA HAYAT VE EMEKLİLİK A.Ş.",
    "AGROT.IS": "AGROTECH YÜKSEK TEKNOLOJİ VE YATIRIM A.Ş.",
    "AAGYO.IS": "AĞAOĞLU AVRASYA GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "AHGAZ.IS": "AHLATCI DOĞAL GAZ DAĞITIM ENERJİ VE YATIRIM A.Ş.",
    "AKBNK.IS": "AKBANK T.A.Ş.",
    "AKCNS.IS": "AKÇANSA ÇİMENTO SANAYİ VE TİCARET A.Ş.",
    "AKFGY.IS": "AKFEN GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "AKFIS.IS": "AKFEN İNŞAAT TURİZM VE TİCARET A.Ş.",
    "AKFYE.IS": "AKFEN YENİLENEBİLİR ENERJİ A.Ş.",
    "AKSGY.IS": "AKİŞ GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "AKSA.IS": "AKSA AKRİLİK KİMYA SANAYİİ A.Ş.",
    "AKSEN.IS": "AKSA ENERJİ ÜRETİM A.Ş.",
    "AKGRT.IS": "AKSİGORTA A.Ş.",
    "ALGYO.IS": "ALARKO GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "ALARK.IS": "ALARKO HOLDİNG A.Ş.",
    "ALBRK.IS": "ALBARAKA TÜRK KATILIM BANKASI A.Ş.",
    "ALK.IS": "ALBARAKA TÜRK KATILIM BANKASI A.Ş.",
    "ALBTN.IS": "ALBAYRAK HAZIR BETON SANAYİ VE TİCARET A.Ş.",
    "ALFAS.IS": "ALFA SOLAR ENERJİ SANAYİ VE TİCARET A.Ş.",
    "ALTNY.IS": "ALTINAY SAVUNMA TEKNOLOJİLERİ A.Ş.",
    "ANSGR.IS": "ANADOLU ANONİM TÜRK SİGORTA ŞİRKETİ",
    "ANHYT.IS": "ANADOLU HAYAT EMEKLİLİK A.Ş.",
    "ASUZU.IS": "ANADOLU ISUZU OTOMOTİV SANAYİ VE TİCARET A.Ş."
}

ANA_PAZAR = {
    "ACSEL.IS": "ACISELSAN ACIPAYAM SELÜLOZ SANAYİ VE TİCARET A.Ş.",
    "ADESE.IS": "ADESE GAYRİMENKUL YATIRIM A.Ş.",
    "AFYON.IS": "AFYON ÇİMENTO SANAYİ T.A.Ş.",
    "AHSGY.IS": "AHES GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "AKENR.IS": "AKENERJİ ELEKTRİK ÜRETİM A.Ş.",
    "AKHAN.IS": "AKHAN UN FABRİKASI VE TARIM ÜRÜNLERİ GIDA SANAYİ TİCARET A.Ş.",
    "AKMGY.IS": "AKMERKEZ GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
    "AKSUE.IS": "AKSU ENERJİ VE TİCARET A.Ş.",
    "ALCAR.IS": "ALARKO CARRIER SANAYİ VE TİCARET A.Ş.",
    "ALCTL.IS": "ALCATEL LUCENT TELETAŞ TELEKOMÜNİKASYON A.Ş.",
    "ALKIM.IS": "ALKİM ALKALİ KİMYA A.Ş.",
    "ALKA.IS": "ALKİM KAĞIT SANAYİ VE TİCARET A.Ş.",
    "AYCES.IS": "ALTIN YUNUS ÇEŞME TURİSTİK TESİSLER A.Ş.",
    "ALKLC.IS": "ALTINKILIÇ GIDA VE SÜT SANAYİ TİCARET A.Ş.",
    "ANGEN.IS": "ANATOLİA TANI VE BİYOTEKNOLOJİ ÜRÜNLERİ ARAŞTIRMA GELİŞTİRME SANAYİ VE TİCARET A.Ş.",
    "ANELE.IS": "ANEL ELEKTRİK PROJE TAAHHÜT VE TİCARET A.Ş."
}

# Yıldız + Ana Pazar (izleme evreni)
YILDIZ_ANA = {**YILDIZ_PAZAR, **ANA_PAZAR}
